
# Site settings
title: Snigdha's Perception
email: snigdhakumari7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   This is how I think, understand and interpret things.... 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skamaraj.github.io" # the base hostname & protocol for your site
twitter_username: skamaraj785
github_username:  skamaraj

# Build settings
markdown: kramdown
